markdown:		redcarpet
highlighter:	true

permalink:		pretty

title: 			Blogging for the Byrds!
tagline:		Documents to help this Byrd remember how to fly!

author:
   name:		Bryan Byrd
   email:		bryanjebyrd@gmail.com
   github:		BBird40
   twitter: 	bryanjebyrd
