markdown:		redcarpet
highlighter:	true

# setup
paginate:		1
baseurl:		'/'
permalink:		pretty
title: 			byrd's eye view.
description:	learning to fly.
# tagline:		learning to fly.

author:
   name:		Bryan Byrd
   email:		bryanjebyrd@gmail.com
   github:		BBird40
   twitter: 	bryanjebyrd
