markdown:		kramdown
highlighter:	rouge
gems:   [jekyll-paginate]

# setup
paginate:		1
baseurl:		'/'
permalink:		pretty
title: 			byrd's eye view.
description:	learning to fly.
# tagline:		learning to fly.

author:
   name:		Bryan Byrd
   email:		bryanjebyrd@gmail.com
   linkedin:	https://www.linkedin.com/pub/bryan-byrd/46/772/973
   github:		https://github.com/BBird40
   twitter: 	https://twitter.com/bryanjebyrd
